title: uarchlabs
description: Open source high performance hardware design
url: "https://uarchlabs.github.io"
baseurl: ""

permalink: /blog/:title/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md
  - docs/
  - Gemfile
  - Gemfile.lock
  - .gitignore

